# Generated by Django 3.2.10 on 2021-12-30 08:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('catalog_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('path', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('containerType', models.CharField(blank=True, max_length=100, null=True)),
                ('datasetType', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('path', models.CharField(max_length=100, unique=True)),
                ('tag', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(null=True)),
                ('sql', models.TextField()),
                ('sqlContext', models.CharField(max_length=100)),
                ('fields', models.TextField()),
                ('parent_datasets', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('reflection_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('currentSizeBytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('totalSizeBytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField()),
                ('arrowCachingEnabled', models.BooleanField(default=False)),
                ('status', models.JSONField(blank=True, null=True)),
                ('displayFields', models.TextField(blank=True, help_text='Leave Blank to Select all Fields in the Dataset', null=True)),
                ('partitionDistributionStrategy', models.CharField(blank=True, help_text='Leave Blank for Default Selection', max_length=15, null=True)),
                ('datasetId', models.ForeignKey(db_column='datasetId', on_delete=django.db.models.deletion.CASCADE, to='dremio_controller.dataset', verbose_name='Parent Dataset')),
                ('scheduled_crontab', models.ForeignKey(blank=True, help_text='Crontab Schedule to run the task on.', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule', verbose_name='Crontab Schedule')),
            ],
        ),
    ]
