"""
Django settings for bicon project.

Generated by 'django-admin startproject' using Django 3.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

import django
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y0!-im-%g^&!c*6pqqgfwlxav%q2f!ogwd@rnd)8if#e8%23d!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Start adding apps
    'rest_framework',
    'django_celery_beat',
    'bicon',
    'dremio_controller'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bicon.urls'

TEMP_DIR = BASE_DIR / 'templates'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMP_DIR,
                 django.__path__[0] + '/forms/templates'  # customize template in Django Widgets
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bicon.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'OPTIONS': {
            'port': int(os.getenv('DB_PORT', 3306)),
            'host': os.getenv('DB_HOST', 'localhost'),
            'db': os.getenv('DB_NAME', 'bicon'),
            'user': os.getenv('DB_USER', 'daniel'),
            'passwd': os.getenv('DB_PASS', 'testing1234')
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_DIR = BASE_DIR / 'static'
STATIC_URL = '/static/'
# STATIC_ROOT = 'static'
STATICFILES_DIRS = [
    STATIC_DIR,
    BASE_DIR / 'bicon/dremio_controller',
    # BASE_DIR / 'plotly_django/static',
    # BASE_DIR / 'authapp/templates/static'
]

# STATICFILES_FINDERS = [
#     'django.contrib.staticfiles.finders.FileSystemFinder',
#     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#     # django_plotly_dash
#     'django_plotly_dash.finders.DashAssetFinder',
#     'django_plotly_dash.finders.DashComponentFinder'
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

###################################################################################

# # DJANGO-PLOTLY-DASH
# CRISPY_TEMPLATE_PACK = 'bootstrap4'
# ASGI_APPLICATION = 'plotly_django.routing.application'
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             'hosts': [('127.0.0.1', 6379), ],
#         },
#     },
# }
# X_FRAME_OPTIONS = 'SAMEORIGIN'

# PLOTLY_COMPONENTS = [
#     'dash',
#     # 'dash_core_components',
#     # 'dash_html_components',
#     'dash_renderer',
#     'dpd_components'
# ]

# CELERY SETTINGS
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379')
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_TIMEZONE = "Asia/Ho_Chi_Minh"
# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30 * 60
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'

# ### DJANGO REST FRAMEWORK
REST_FRAMEWORK = {
    # Login API
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        # 'knox.auth.TokenAuthentication'
    ],
    # 'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    # Adding Default Pagination for API View
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# AUTH_USER_MODEL = 'accounts.Users'
# LOGIN_URL = 'accounts/login/'
# ### CSV DOWNLOAD
# DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000000

# SUPERSET_URL = os.getenv('SUPERSET_URL', 'http://localhost:8088')
# SUPERSET_BASE_URL = SUPERSET_URL + '/api/v1'
# DRIVER_CHROME = os.getenv('DRIVER_CHROME', '')

# # authapp
# LOGIN_REDIRECT_URL = 'authapp:dashboard'
# LOGIN_URL = 'login'
# LOGOUT_URL = 'logout'
# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
# EMAIL_FILE_PATH = str(BASE_DIR.joinpath('sent_emails'))

# DREMIO CREDENTIALS
DREMIO_BASE_URL = os.getenv('DREMIO_BASE_URL', 'http://dremio.bi.stuffio.com')
DREMIO_USER = os.getenv('DREMIO_USER', '')
DREMIO_PW = os.getenv('DREMIO_PW', '')
DATA_DIR = os.getenv('DATA_DIR', '/data/')
